import { motion } from "framer-motion";
import ReactMarkdown from "react-markdown";
import { Bot, Sparkles } from "lucide-react";

function ReviewCard({ review }) {

    return (

        <motion.div
            whileHover={{ y: -4 }}
            transition={{ duration: 0.2 }}
            className="bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden"
        >

            {/* Header */}

            <div className="border-b border-slate-800 p-6 flex justify-between items-center">

                <div className="flex items-center gap-3">

                    <div className="bg-blue-600/20 p-3 rounded-xl">

                        <Bot className="text-blue-400" />

                    </div>

                    <div>

                        <h2 className="text-2xl font-bold">

                            AI Repository Review

                        </h2>

                        <p className="text-slate-400 text-sm">

                            Generated by AI

                        </p>

                    </div>

                </div>

            </div>

            {/* Review */}

            <div className="p-8 prose prose-invert max-w-none">

                <ReactMarkdown>

                    {review}

                </ReactMarkdown>

            </div>

            {/* Footer */}

            <div className="border-t border-slate-800 p-5 flex items-center gap-2 text-slate-400">

                <Sparkles size={18} />

                AI generated repository analysis

            </div>

        </motion.div>

    );

}

export default ReviewCard;